### ISSUE TITLE
m3u8播放不出来！

### ISSUE THREAD

**Issue by pengqiuyuan** [jackzhang1204/sewise-player#4]
网页可以不断接收ts文件，但是播放不出来

```
    <div style="width: 600px;height: 400px;">
        <script type="text/javascript" src="../player/sewise.player.min.js?server=vod&type=m3u8&videourl=http://*********/hls/test.m3u8&sourceid=&autostart=true&starttime=0&lang=en_US&logo=http://onvod.sewise.com/libs/swfplayer/skin/images/logo.png&title=Play-M3u8&buffer=5&claritybutton=disable&skin=vodWhite"></script>
    </div>
```

![qq20140718120736](https://cloud.githubusercontent.com/assets/4953205/3622387/a4bc44ee-0e31-11e4-804d-6d5907e92eb9.png)

**Comment by aiyuchen** [comment]
试了，真的可以播放AES-128加密的视频。好激动，换了好多个播放器了，总算找到一个OK的，good，研究起来~支持~~~~~~~

**Comment by usydapeng** [comment]
怎么去logo

**Comment by kobe0116** [comment]
使用的时候 crossdomain.xml 404 (Not Found)报这样的错误时什么原因

**Comment by jackyyyy** [comment]
jackzhang，您上面的链接点过去之后谷歌浏览器报错，不知道是什么原因，
1、普通m3u8： http://jackzhang1204.github.io/sewise/sewise_player/demos/flash_m3u8.html
2、加密m3u8：http://jackzhang1204.github.io/sewise/sewise_player/demos/flash_m3u8_aes_128.html

可以看看是什么原因么？
