### ISSUE TITLE
chrome的手机模式下报错

### ISSUE THREAD

**Issue by hsyan2008** [jackzhang1204/sewise-player#46]
在chrome的手机模式下报错信息如下
Uncaught (in promise) DOMException: Failed to load because no supported source was found.

**Comment by KingYoung87** [comment]
这个应该是你添加的地址跟设置的播放器类型不一致导致的吧

**Comment by hsyan2008** [comment]
@KingYoung87 用手机浏览器就可以

**Comment by KingYoung87** [comment]
你是什么手机浏览器？

**Comment by hsyan2008** [comment]
@KingYoung87 手机浏览器都可以

**Comment by chenhengtong** [comment]
我用手机， 苹果可以，安卓的播放不了， 有解决的吗。

**Comment by hy20160705** [comment]
大兄弟最后这个问题解决了吗

**Comment by hy20160705** [comment]
怎么解决的  求指教

**Comment by hsyan2008** [comment]
最近没在用这个了，都是自己写的，所以以上问题暂时未解决

**Comment by hy20160705** [comment]
你的使用场景是怎样的
我的是后台给我一个流地址  我根据这个流地址去播放
