### ISSUE TITLE
sewise.player.min.js未压缩的文件，有没有人可以提供，感谢！！！

### ISSUE THREAD

**Issue by 1995hjh** [jackzhang1204/sewise-player#62]
sewise.player.min.js未压缩的文件，最好包含注释，有没有人分享的？

**Comment by hefeng1208** [comment]
@1995hjh 这个好像没有完全开源，源代码没有提供，只有压缩文件。

**Comment by 1995hjh** [comment]
谢谢你的回复，我已经在那个基础上做修改了

**Comment by hefeng1208** [comment]
@1995hjh 可以分享一下你的代码吗？有点唐突，不过确实很需要如果可以的话，多谢啦

**Comment by 1995hjh** [comment]
@hefeng1208 已经在我的github里，sewise-player-moudle，sewise视频播放器插件的二次封装这个
